[versions]
agp = "8.6.1"
kotlin = "1.9.24"
ksp = "1.9.24-1.0.20"
compileSdk = "34"
minSdk = "24"
targetSdk = "34"
compose-bom = "2024.09.01"
compose-compiler = "1.5.14"
core-ktx = "1.13.1"
activity-compose = "1.9.2"
navigation-compose = "2.8.1"
lifecycle-compose = "2.8.3"
room = "2.6.1"
firebase-bom = "33.3.0"
retrofit = "2.11.0"
okhttp = "4.12.0"
okhttp-logging = "4.12.0"
coil = "2.7.0"
maps = "18.2.0"
location = "21.3.0"
mapsCompose = "4.3.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-icons = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.6.8" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp-logging" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "maps" }
location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "location" }
maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "mapsCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.24-1.0.20" }
google-services = { id = "com.google.gms.google-services", version = "4.4.4" }